export enum Weapon {
  CHAIN_SWORD = 'CHAIN_SWORD',
  POWER_AXE = 'POWER_AXE',
  POWER_SWORD = 'POWER_SWORD',
  ASSAULT_BOLTER = 'ASSAULT_BOLTER',
  HEAVY_BOLT_RIFLE = 'HEAVY_BOLT_RIFLE',
  PLASMA_GUN = 'PLASMA_GUN',
  AUTOCANNON = 'AUTOCANNON',
  SNIPER_RIFLE = 'SNIPER_RIFLE',
  SHOTGUN = 'SHOTGUN',
}

export enum Rank {
  ASPIRANT = 'ASPIRANT',
  NEOPHYTE = 'NEOPHYTE',
  VANGUARD = 'VANGUARD',
  BATTLE_BROTHER = 'BATTLE_BROTHER',
  SERGEANT = 'SERGEANT',
  LIEUTENANT = 'LIEUTENANT',
  CAPTAIN = 'CAPTAIN',
  CHAPTER_MASTER = 'CHAPTER_MASTER',
}
